source "https://cdn.cocoapods.org/"
source "https://github.com/livekit/podspecs"
source "https://github.com/vopenia-io/pod-repo"

target 'appIos' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "16.0"
      end
    end
  end
end
